name: Release

on:
  workflow_run:
    workflows: ['test']
    branches: ['master']
    types:
      - completed

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm install
      - run: npm run build
      - name: Release
        run: |
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          npm run release -- patch
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
